apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: argocd
    name: in-cluster
  source:
    path: argocd/project
    repoURL: https://github.com/devopscope/eks-tf-cw.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
