---
apiVersion: v1
kind: Secret
metadata:
  name: nodejs-express-mysql-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:devopscope/nodejs-express-mysql.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACC9halKPICT203cdzvFpGawF/EZBAzI0JwINFUALX0eCQAAAJhsCiQ7bAok
    OwAAAAtzc2gtZWQyNTUxOQAAACC9halKPICT203cdzvFpGawF/EZBAzI0JwINFUALX0eCQ
    AAAECScgNICyTDkilNAC1nqLj1g6qHPJIfQSVijaO/cj4iIb2FqUo8gJPbTdx3O8WkZrAX
    8RkEDMjQnAg0VQAtfR4JAAAAFWFyZ29jZEBkZXZvcHNjb3BlLmNvbQ==
    -----END OPENSSH PRIVATE KEY-----  
  insecure: "true"
  enableLfs: "true"
