---
apiVersion: v1
kind: Secret
metadata:
  name: nodejs-express-mysql-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:devopscope/nodejs-express-mysql.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACBOsUfYtZEUzsP67BrE43y5Oi59ROUOUle1bXx115jIXgAAAJATsvfPE7L3
    zwAAAAtzc2gtZWQyNTUxOQAAACBOsUfYtZEUzsP67BrE43y5Oi59ROUOUle1bXx115jIXg
    AAAEDQrePHr9SnO8c6g1301tagXOeM/VHJkBj1X1ePOt6V0k6xR9i1kRTOw/rsGsTjfLk6
    Ln1E5Q5SV7VtfHXXmMheAAAABmFyZ29jZAECAwQFBgc=
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"
