apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd # Ensure this is the Argo CD namespace
spec:
  refreshInterval: 1h # How often ESO should check for updates (adjust as needed)
  secretStoreRef:
    name: aws-secrets-manager # Replace with the name of your SecretStore connecting to AWS
    kind: ClusterSecretStore
  target:
    name: argocd-notifications-secret # The name of the Kubernetes Secret to create
    creationPolicy: Owner # The ExternalSecret owns and manages the lifecycle
  data:
    - secretKey: slack-token # The key in the Kubernetes Secret
      remote:
        key: argo-cd-slack-token # The name of the secret in AWS Secrets Manager
        property: slack_token # (Optional) If the AWS secret is JSON, the key to extract